# Generated by Django 5.0.4 on 2024-05-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(default='default_img/default_book_img.png', upload_to='library/'),
        ),
    ]
